# Generated by Django 4.1 on 2022-09-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('name_of_owner', models.CharField(max_length=50)),
                ('number_of_rooms', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('current_lease_period', models.DateField()),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.buildingtype')),
            ],
        ),
    ]
