# Generated by Django 4.1 on 2023-01-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Room Status',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Room Type',
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='buildingtype',
            options={'verbose_name_plural': 'Building Type'},
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('meter_number', models.CharField(max_length=16)),
                ('account_number', models.IntegerField(max_length=10)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.building')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.roomstatus')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
