# Generated by Django 4.2.6 on 2023-10-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('id_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'ID Types',
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Room Status',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Room Type',
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='buildingtype',
            options={'verbose_name_plural': 'Building Type'},
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('meter_number', models.CharField(max_length=16)),
                ('account_number', models.IntegerField()),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.building')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.roomstatus')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('comment', models.CharField(max_length=250)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.customer')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.room')),
            ],
            options={
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='building_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.building'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.idtype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.room'),
        ),
    ]
