# Generated by Django 4.1 on 2023-01-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_roomstatus_roomtype_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='meter_number',
            field=models.CharField(max_length=17),
        ),
    ]
