# Generated by Django 4.1 on 2023-01-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_room_account_number_alter_room_meter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='meter_number',
            field=models.CharField(max_length=16),
        ),
    ]
