# Generated by Django 4.1 on 2023-01-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_room_meter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'ID Types',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.building')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.idtype')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.room')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
