# Generated by Django 4.2.4 on 2023-09-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_idtype_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('comment', models.CharField(max_length=250)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.customer')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.room')),
            ],
            options={
                'verbose_name_plural': 'Receipts',
            },
        ),
    ]
