# Generated by Django 4.2.4 on 2023-09-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_receipt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.AutoField(default=10001, primary_key=True, serialize=False),
        ),
    ]
